package com.example.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.database.entity.DownloadFile;

import com.example.database.greendao.DownloadFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadFileDaoConfig;

    private final DownloadFileDao downloadFileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadFileDaoConfig = daoConfigMap.get(DownloadFileDao.class).clone();
        downloadFileDaoConfig.initIdentityScope(type);

        downloadFileDao = new DownloadFileDao(downloadFileDaoConfig, this);

        registerDao(DownloadFile.class, downloadFileDao);
    }
    
    public void clear() {
        downloadFileDaoConfig.clearIdentityScope();
    }

    public DownloadFileDao getDownloadFileDao() {
        return downloadFileDao;
    }

}
