package com.example.thirdpartydemo.download.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.thirdpartydemo.download.db.entity.DownloadFile;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOWNLOAD_FILE".
*/
public class DownloadFileDao extends AbstractDao<DownloadFile, Long> {

    public static final String TABLENAME = "DOWNLOAD_FILE";

    /**
     * Properties of entity DownloadFile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Thread = new Property(1, int.class, "thread", false, "THREAD");
        public final static Property Start = new Property(2, Long.class, "start", false, "START");
        public final static Property End = new Property(3, Long.class, "end", false, "END");
        public final static Property Process = new Property(4, Long.class, "process", false, "PROCESS");
    }


    public DownloadFileDao(DaoConfig config) {
        super(config);
    }
    
    public DownloadFileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOWNLOAD_FILE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"THREAD\" INTEGER NOT NULL UNIQUE ," + // 1: thread
                "\"START\" INTEGER," + // 2: start
                "\"END\" INTEGER," + // 3: end
                "\"PROCESS\" INTEGER);"); // 4: process
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOWNLOAD_FILE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownloadFile entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getThread());
 
        Long start = entity.getStart();
        if (start != null) {
            stmt.bindLong(3, start);
        }
 
        Long end = entity.getEnd();
        if (end != null) {
            stmt.bindLong(4, end);
        }
 
        Long process = entity.getProcess();
        if (process != null) {
            stmt.bindLong(5, process);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownloadFile entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getThread());
 
        Long start = entity.getStart();
        if (start != null) {
            stmt.bindLong(3, start);
        }
 
        Long end = entity.getEnd();
        if (end != null) {
            stmt.bindLong(4, end);
        }
 
        Long process = entity.getProcess();
        if (process != null) {
            stmt.bindLong(5, process);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DownloadFile readEntity(Cursor cursor, int offset) {
        DownloadFile entity = new DownloadFile( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // thread
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // start
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // end
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // process
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownloadFile entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThread(cursor.getInt(offset + 1));
        entity.setStart(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setEnd(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setProcess(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DownloadFile entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DownloadFile entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DownloadFile entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
